title: API Docs
description: API Docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true

# Define sidebar navigation
nav_order: 1

# Sidebar structure
nav:
  - title: API Docs
    url: /
  - title: API Endpoints
    children:
      - title: Create Memory
        url: /docs/create-memory
      - title: Query Memories
        url: /docs/query-memory
      - title: Chat Completions
        url: /docs/chat-completions
      - title: Supported Models
        url: /docs/supported-models
      - title: Create Memory Field
        url: /docs/create-memory-field
