title: EMFDash API
description: API Documentation for EMFDash
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme


# Enable the navigation sidebar
just_the_docs:
  search_enabled: true
  navigation:
    - title: API Documentation
      url: /
    - title: Create Memory
      url: /fields/:fieldId/memories
    - title: Query Memories
      url: /fields/:fieldId/memories/query
    - title: Chat Completions
      url: /v1/chat/completions
