title: API Docs
description: API Documentation for Sentech
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true

# Navigation structure
nav_external_links:
  - title: "Sentech.AI"
    url: "https://sentech.ai"
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
nav:
  - title: "API Docs"
    url: "/"
  - title: "Create Field"
    url: "/create-memory-field"
  - title: "Create Memory"
    url: "/create-memory"
  - title: "Query Memory"
    url: "/query-memory"
  - title: "Chat Completion"
    url: "/chat-completions"
  - title: "Supported Models"
    url: "/supported-models"

    
