title: API Docs
description: API Documentation for Sentech
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true

# Navigation structure
nav:
  - title: "Main"
    url: "https://sentech.ai"
  - title: "API Docs"
    url: "/"
  - title: "Create Field"
    url: "/create-memory-field"
  - title: "Create Memory"
    url: "/create-memory"
  - title: "Query Memory"
    url: "/query-memory"
  - title: "Chat Completion"
    url: "/chat-completions"
  - title: "Supported Models"
    url: "/supported-models"

    
