title: API Docs
description: API Documentation for Sentech
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true

# Navigation structure
nav:
  - title: "API Docs"
    url: "/"
  - title: "Create Memory"
    url: "//create-memory"
  - title: "API Endpoints"
    children:
      - title: "Create Memory"
        url: "/create-memory"
      - title: "Query Memories"
        url: "/query-memory"
      - title: "Chat Completions"
        url: "/chat-completions"
      - title: "Supported Models"
        url: "/supported-models"
      - title: "Create Memory Field"
        url: "/create-memory-field"
